#!/usr/bin/env bash

if  grep "NetworkManager" /etc/resolv.conf > /dev/null
then	
	echo "# Generated by shecan" > /etc/resolv.conf
	echo "search lan" >> /etc/resolv.conf 
	echo "nameserver 178.22.122.100" >> /etc/resolv.conf 
	echo "nameserver 185.51.200.2" >> /etc/resolv.conf 
	figlet "Activated"
else
	echo "# Generated by NetworkManager" > /etc/resolv.conf
	echo "search lan" >> /etc/resolv.conf 
	echo "nameserver 10.255.255.254" >> /etc/resolv.conf 
	echo "nameserver 8.8.8.8" >> /etc/resolv.conf 
	figlet "Deactivated"
fi
